ratings:
  paths:
  - lib/**
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
  fixme:
    enabled: true
