engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 50
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
  fixme:
    enabled: true
