language: node_js
node_js:
- '5'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: kripod@protonmail.com
  api_key:
    secure: ycFkwt5WgNcDWTD6Mbr332L/xUtNZaBOe2xjBbcapPt8GbHikH++3T2b8eoeLdIh0pTB95ZtXLjcA8ln4aqpAWqdvMdRtEg44e+snwQDnUTvm76UmLTi/6yFl156CKJ5mJ/fBCvgHjjdHhyFDuUvMmKfVKVGVHt5IQBWNmxvYFVdFh3+IXRzIWTz3WCvt7H/AJP3eFUVlz8Qoo8sWYJj4nhNLz93C8LnViB10ZkQormF0zJVtNIIk/pPuZNxgK9OG1/di7ZGLXDs1epReY6+k/0i8hzJ456cVDdj8g1fUzDnk9wxl6me2n87ps6TbqIwsQ9+x+gGz/80LDCRNrDwrS6JYlJp9CNj550odWFafwCyidL9Tkolsl2LAyukanXH8oBgY0D9hSUZ09ZawH/hViEWSiE8K+W0c9hiiIUVMrfO+y5/u2Em4PZWtaBz2N7gF0r7whU9hunW+c8Avx7cQmsJO+lEhjmcirWvMMKq03KW4gegwzUt7y/72BdvBYxXaAxv+zV2+k2hM237dOKYnz5DTo/pfzcMhad/l5Owm3m1JadNGU1OixueWrp1f5r7IoT9oNzo2qKcJ/G1HgCX8dyzbaMsIUURNnJmLo2yAJzAK1MAvzjDkWE0vkgA60hhxYXVgXTJ8/u93bh/qkmvg8ttwHm4XSwlXPJe9YPMRsQ=
  on:
    tags: true
addons:
  code_climate:
    repo_token:
      secure: XrGX2aw6HpR/VzOElrMBCpzWSXtVbyu9UGf3REwwIEUJJMt3ylUfYVzL6jayHCSgunXXSo/40OI1LB1HofOOY+tAEu2vJXECHHiD/6MRJdrBspjO1SCoFgtXF0pZ9WEe9Z29B3TcBuGGxrQRjHQPaar2SFO6LrSOLx/zHJvAimHOjsXlLKPdIKMPW41wzUzw706xFkUsrjrwSZiKqv44uJ7NOwTxupR+Y7wLfVKs7sd4oFkYm9ZpMCQY707YPZWXpZN4YpvLQ530481tpRms9ej3RgdfL65sd/2ijLX9UGYfghdmGvXHhz0rsG7zExZIEcdE+I9KfO8+mcaYediTZRUnDdffqDaQIB2IksaZj1eaJ95rQZMYizE7p7pfvetp3I8EZY2N37jyvT67D4kQa2Vf1PM9aEOXLdKxpX7D4FaFgG/czvCwEGuyrsKHVJPp02KN93aoBTKITVpYiWuFWRM2JrzveH7jXzuchdQNqoF2cIblZ4c48IXjeBJGnX4V8RufQXXQT8Y7KoZ2MAsO8kKIJgr0m4V83H5VX8HkX3n/0qi9PvGL6HMSK+K2hIf9wQHSRAVaxQOEuQxEcHPduhAI6Ci/ew3d+spL+YEvXKU5fEbPR3SEoZqOaXZRrlMLZPmDYOr3i/xxtlBkbbc9MduMWJhYWHoQWbZBFXf+5Cs=
